---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    settings:
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      envs:
        git_auth
      script:
        - export token=$git_auth
        - cd /root/temp/oms-bi-deploys
        - git pull https://oauth:${token}@github.com/RichDataTeam/oms-bi-deploy
        
        
