---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: env
    image: alpine
    commands:
      - env
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      GIT_TOKEN:
        from_secret: git_auth
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      script_stop: true
      envs:
        - GIT_TOKEN
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
      script:
        - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
        - cd /root/oms-bi-deploy
        - git pull https://oauth2:$GIT_TOKEN@github.com/RichDataTeam/oms-bi-deploy.git
        - env
        # - make aurora-test
        # - cd sodmsoa/1231dasd123/123123/213123/213123
  - name: notification
    image: lddsb/drone-dingtalk-message
    when:
      status:
      - success
      - failure
    settings:
      token:
        from_secret: dingtalk_message_token
      type: markdown
