---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      git_token:
        from_secret: git_auth
      commiter: ${GIT_AUTHOR_EMAIL}
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      envs:
        - git_token
        - commiter
      script:
        - export GIT_TOKEN=$GIT_TOKEN
        - echo $git_token
        - echo $commiter
        - env
    commands:
      - export GIT_TOKEN=$GIT_TOKEN
      - echo $git_token
      - echo $commiter
      - env  
      