---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      GIT_TOKEN:
        from_secret: git_auth
    settings:
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      envs:
        - GIT_TOKEN
      script:
        - echo $GIT_TOKEN
        - export GIT_TOKEN_1=$GIT_TOKEN
        - env
        - cd /root/temp/oms-bi-deploy
        - git pull https://oauth:${GIT_TOKEN_1}@github.com/RichDataTeam/oms-bi-deploy

