---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh

    when:
      branch: master
    settings:
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      envs:
        - git_auth
      script:
        - export GIT_AUTH=$GIT_AUTH
        - cd /root/temp/oms-bi-deploy
        - git pull https://oauth:${GIT_AUTH}@github.com/RichDataTeam/oms-bi-deploy