---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      GIT_TOKEN:
        from_secret: git_auth
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      envs:
        - GIT_TOKEN
      script:
        - cd /root/oms-bi-deploy
        - git pull https://oauth:$GIT_TOKEN@github.com/RichDataTeam/oms-bi-deploy.git
        - make aurora-test