---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      git_token:
        from_secret: git_auth
      commiter: ${GIT_AUTHOR_EMAIL}
    envs:
      - git_token
      - commiter
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      envs:
        - git_token
        - commiter
      script:
        - echo $git_token && echo $commiter
        - echo ${git_token} && echo ${commiter}
        - echo $GIT_TOKEN && echo $COMMITER
        - echo ${GIT_TOKEN} && echo ${COMMITER}
        - env