---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: env
    image: alpine
    commands:
      - env
  - name: my-plugin
    image: kitkit/drone-plugin-test
    environment:
      REQ_URL: https://apis.map.qq.com/ws/geocoder/v1/?key=TIRBZ-FUKCP-Q3JD6-L52ZG-RMB4V-UVBRV&address=重庆市渝北区北大资源博雅东
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      GIT_TOKEN:
        from_secret: git_auth
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      script_stop: true
      envs:
        - GIT_TOKEN
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
      script:
        - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
        - cd /root/oms-bi-deploy
        # - git pull https://oauth2:$GIT_TOKEN@github.com/RichDataTeam/oms-bi-deploy.git
        - env
        # - make aurora-test
        # - cd sodmsoa/1231dasd123/123123/213123/213123
  - name: notification
    image: lddsb/drone-dingtalk-message
    when:
      status:
      - success
      - failure
    settings:
      token:
        from_secret: dingtalk_message_token
      type: markdown
    commands:
      - echo '### [TPL_REPO_SHORT_NAME] build [TPL_BUILD_STATUS] (`takes [TPL_BUILD_CONSUMING]s`)\n' > /app/markdown.tpl
      - echo '![RUNOOB 图标](http://static.runoob.com/images/runoob-logo.png)\n' >> /app/markdown.tpl
      - echo '[TPL_COMMIT_MSG]\n' >> /app/markdown.tpl
      - echo '[[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])\n' >> /app/markdown.tpl
      - echo '[[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])\n' >> /app/markdown.tpl
      - echo '[Click To The Build Detail Page [TPL_STATUS_EMOTICON]]([TPL_BUILD_LINK])\n' >> /app/markdown.tpl
      - /bin/drone-dingtalk
