---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
  event:
    - push

steps:
  - name: deploy.test
    image: appleboy/drone-ssh
    when:
      branch: master
    environment:
      GIT_TOKEN:
        from_secret: git_auth
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      debug: true
      host: aurora-test.cqrqmy.com
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      script_stop: true
      envs:
        - GIT_TOKEN
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
      # script:
        # - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
        # - cd /root/oms-bi-deploy
        # - git pull https://oauth2:$GIT_TOKEN@github.com/RichDataTeam/oms-bi-deploy.git
        # - make aurora-test
      commands:
        - env
  - name: notify
    image: lddsb/drone-dingtalk-message
    when:
      status:
      - success
      - failure
    settings:
      token: 3bccb475232b974384be6c4e6d90c79577ace5f41782a1df5d812085d076b683
      type: markdown
      secret: SECecb6ad4fb693f5a0946174dae96cbf2ce7ff1ef8a0139103ed47cefc8327b502